version: "3"
services:
  svrchan:
    build: .
    container_name: svrchan
    volumes:
      - /www/svrchan:/app
    working_dir: /app
    networks: 
      - default
    ports: 
      - ${SVRCHAN_PORT:-8000}:8000
    restart: always
    logging:
      options:
        max-size: "10m"
    environment: 
      - SVRCHAN_MAIL_FROM=${MAIL_FROM:-"Henry TIAN <chariothy@gmail.com>"}
      - SVRCHAN_MAIL_TO=${MAIL_TO:-"Henry TIAN <chariothy@gmail.com>"}
      - SVRCHAN_SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SVRCHAN_SMTP_PORT=${SMTP_PORT:-25}
      - SVRCHAN_SMTP_USER=${SMTP_USER:-chariothy@gmail.com}
      - SVRCHAN_SMTP_PWD=${SMTP_PWD}
      - SVRCHAN_DINGTALK_TOKEN=${DINGTALK_TOKEN}
      - SVRCHAN_DINGTALK_SECRET=${DINGTALK_SECRET}
      - ENV=${ENV}
    command: python server.py
    